name: luci-app-passwall CI
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  watch:
#    types: started
#  schedule:
#    - cron: 0 21 */7 * * 

      
jobs:
  build:
    runs-on: ubuntu-18.04
    
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    
    - name: Download and untar sdk
      run: |
        wget $URL
        tar xvJf openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    
    - name: Configure sdk
      run: cp ./config openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64/.config
      
    - name: Install dependencies
      run: |
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

        
    - name: Clone package
      run: |
        ls
        git clone -b master https://github.com/kenzok8/openwrt-packages/tree/master/luci-app-passwall.git ./openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64/luci-app-passwall
        ls
    - name: Build ipk
      run: |
        cd openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64
        make package/luci-app-passwall/compile V=99
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: luci-app-passwall
        path: openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64/bin/packages/x86_64/base
